version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: investments-app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: .
      dockerfile: investment-dashboard/Dockerfile
    ports:
      - "8443:8443"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 👈 On injecte les certificats générés par Tailscale sur ton mini-PC dans le conteneur :
      - /home/bryan/certificates/bryannas.tail3a42eb.ts.net.crt:/etc/nginx/ssl/dashboard.crt
      - /home/bryan/certificates/bryannas.tail3a42eb.ts.net.key:/etc/nginx/ssl/dashboard.key

volumes:
  sqlite_data:
